"""Tabelas primordiais

Revision ID: 5eefcf93fbc3
Revises: 
Create Date: 2025-12-17 17:58:53.528450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eefcf93fbc3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comanda',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('mesa_num', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('titulo', sa.String(length=40), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('disponivel', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('titulo')
    )
    op.create_table('comanda_produto',
    sa.Column('id_comanda', sa.Integer(), nullable=False),
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantidade > 0', name='ck_quantidade_positive'),
    sa.ForeignKeyConstraint(['id_comanda'], ['comanda.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id_comanda', 'id_produto')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comanda_produto')
    op.drop_table('produto')
    op.drop_table('comanda')
    # ### end Alembic commands ###
